desc NAVIO;
desc CARGA;
desc OPERACAO;
desc CLIENTE;
desc CARREGAMENTO;
desc MOTORISTA;
desc USUARIO;
desc CARGA;
desc STATUS_CARGA;
desc STATUS_CARREGAMENTO;
desc COMPLEMENTO_PAR;
desc STATUS_DOCUMENTO;
desc PERIODO;
desc PERIODO_OPERACAO;
desc PARALISACAO;

SELECT 
CA.ID_CARREGAMENTO,
MT.NOME_MOTORISTA,
CA.PLACA_CAVALO,
CA.PESO_TARA,
CA.PLACA_CARRETA,
CA.DATA_CADASTRO 
FROM CARREGAMENTO CA
INNER JOIN MOTORISTA MT ON MT.COD_MOTORISTA = CA.COD_MOTORISTA
    WHERE COD_OPERACAO = 34;

select * from MOTORISTA;
select * from NAVIO;
select * from AGENTE;
select * from CLIENTE;
select * from PRODUTO;
select * from EMPRESA;
select * from BERCO;
select * from EQUIPAMENTO;
select * from USUARIO;
select * from CARGA;
select * from CARREGAMENTO;
select * from OPERACAO;
select * from TRANSPORTADORA;
select * from STATUS_CARGA;
select * from STATUS_CARREGAMENTO;
select * from STATUS_DOCUMENTO;
select * from PERIODO;
select * from PERIODO_OPERACAO;
select * from PARALISACAO;
select * from MOTIVO_PAR;
select * from COMPLEMENTO_PAR;

-- berço sera informado no form de abertura periodo ou no dash

INSERT INTO `PARALISACAO` (`COD_OPERACAO`, `SEQ_PERIODO_OP`, `COD_MOTIVO`, `COD_COMPL`, `OBSERVACO`, `DATA_INICIO`, `USUARIO`, `DAT_CADASTRO`)
VALUES ('13', '1', '7', '1', 'TESTANDO...', '2023-01-25 00:00', 'MAGUIAR', '2023-01-25 00:00');

SELECT
            OP.SEQ_PERIODO_OP,
            OP.COD_OPERACAO,
            N.NOME_NAVIO,
            P.STATUS_OPERACAO,
            PE.DEN_PERIODO,
            SUM(CA.QTDE_MANIFESTADA) as MANIFESTADO,
            OP.DAT_INI_PERIODO AS INI_PERIODO,
            BE.NOME_BERCO,
            MO.DESC_EQUIPAMENTO AS MOEGA
        FROM
            PERIODO_OPERACAO OP
            INNER JOIN PERIODO PE ON PE.COD_PERIODO = OP.COD_PERIODO
            INNER JOIN OPERACAO P ON P.COD_OPERACAO = OP.COD_OPERACAO
            INNER JOIN CARGA CA ON CA.COD_OPERACAO = OP.COD_OPERACAO
            INNER JOIN NAVIO N ON N.COD_NAVIO = P.COD_NAVIO
            INNER JOIN BERCO BE ON BE.COD_BERCO = OP.COD_BERCO
            INNER JOIN EQUIPAMENTO MO ON MO.COD_EQUIPAMENTO = OP.COD_MOEGA
        WHERE
            OP.DAT_FIM_PERIODO IS NULL
            AND OP.COD_OPERACAO = '13';



-- dashboard
SELECT OP.SEQ_PERIODO_OP,
       OP.COD_OPERACAO,
       N.NOME_NAVIO,
       P.STATUS_OPERACAO,
       PE.DEN_PERIODO,
       SUM(CA.QTDE_MANIFESTADA) as MANIFESTADO,
       OP.DAT_INI_PERIODO AS INI_PERIODO,
       BE.NOME_BERCO,
       MO.DESC_EQUIPAMENTO AS MOEGA
  FROM PERIODO_OPERACAO OP
 INNER JOIN PERIODO PE
	ON PE.COD_PERIODO = OP.COD_PERIODO
INNER JOIN OPERACAO P
	ON P.COD_OPERACAO = OP.COD_OPERACAO
INNER JOIN CARGA CA
	ON CA.COD_OPERACAO = OP.COD_OPERACAO
INNER JOIN NAVIO N
	ON N.COD_NAVIO = P.COD_NAVIO
 INNER JOIN BERCO BE
    ON BE.COD_BERCO = OP.COD_BERCO
 INNER JOIN EQUIPAMENTO MO
    ON MO.COD_EQUIPAMENTO = OP.COD_MOEGA
 WHERE OP.DAT_FIM_PERIODO IS NULL
   AND OP.COD_OPERACAO = 13;
   
select SUM(QTDE_MANIFESTADA) as MANIFESTADO from CARGA
where COD_OPERACAO = 13; -- NAO USA
   
select SUM(PESO_CARREGADO) as DESCARREGADO from CARREGAMENTO
where COD_OPERACAO = 13 ;
   
   -- paralisacao
   SELECT PA.COD_OPERACAO,
	   PA.SEQ_PERIODO_OP,
	   PA.SEQ_PARALISACAO,
       PA.COD_MOTIVO,
       MP.DESC_MOTIVO,
       PA.COD_COMPL,
	   PA.OBSERVACO,
       PA.DATA_INICIO,
       PA.DATA_TERMINO
  FROM PARALISACAO PA
 INNER JOIN MOTIVO_PAR MP
    ON MP.COD_MOTIVO = PA.COD_MOTIVO
 INNER JOIN COMPLEMENTO_PAR CP
    ON CP.COD_COMPL = PA.COD_COMPL
 WHERE PA.COD_OPERACAO = 13;

